# Generated by Django 3.0.6 on 2020-05-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderMoney', models.FloatField()),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserInfo')),
            ],
        ),
    ]
