# Generated by Django 3.0.6 on 2020-05-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_orderinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_table',
        ),
    ]
