# Generated by Django 3.0.6 on 2020-05-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_product_usergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='products',
            field=models.ManyToManyField(to='userApp.Product'),
        ),
        migrations.DeleteModel(
            name='UserGoods',
        ),
    ]
